### ISSUE TITLE
Sumaform master HEAD: 403 forbidden

### ISSUE THREAD

**Issue by mbologna** [moio/sumaform#234] opened 2017-12-12 16:25 UTC
Checked out HEAD on master, tried a terraform apply:

  name:   "" => "sles15"
  pool:   "" => "default"
  size:   "" => "<computed>"
  source: "" => "http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles15b3.x86_64.qcow2"
Error applying plan:

1 error(s) occurred:

* module.base.libvirt_volume.volumes[8]: 1 error(s) occurred:

* libvirt_volume.volumes.8: Error accessing remote resource: http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles15b3.x86_64.qcow2 - 403 Forbidden

**Comment by mcalmer** [comment] 2017-12-12 16:48
Will be fixed by https://github.com/moio/sumaform/pull/231
I wanted to wait until Beta4 is released to also finalize the official repos.

**Comment by moio** [comment] 2018-02-19 15:29
Can't reproduce this any more, I assume it's fixed.

**Closed by moio** 2018-02-19 15:29 UTC
Labels: bug
