### ISSUE TITLE
unreleased updates improvements in sumaform

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#339] opened 2018-05-23 09:45 UTC

**Comment by ktsamis** [comment] 2018-05-23 10:03
Basically the issue is when failures happen with the unreleased updates enabled we need a way to determine which update is at fault. 

One way would be to have a bot to pick up each update, install it and run the testsuite. This would cause a huge overhead since that would mean dozens of parallel run of the testsuite and we simply don't have the resources for that. I am not sure if this can be done in the cloud but definitely not in physical servers. 

Another is the way we currently have, to have all unreleased updates, run the testsuite and compare the results without the unreleased updates in the testsuite run. If we have differences is where the interesting stuff happens. How to debug which update is at fault in that case? It's pretty much random luck or seeing if there is a really relevant update, e.g postgresql and the failures in the testsuite are psotgresql errors. In that case we still need to do a run without the unreleased updates but with only the specific update to confirm that it's at fault.

**Comment by MalloZup** [comment] 2018-05-23 10:31
@ktsamis you are already using additional_repos and pkg.
What prevent you to implement your 'blacklist' as following?

1) Create a separate job in jenkins. (not for MU)

2) use this specific configuration

```hcl
  additional_repos {
    unreleased_update= "download.suse.de/ibs/SUSE:/Maintenance:/Test:/SLE-SERVER:/12-"SP3:/x86_64/update/
  }

  additional_packages = [ "postgresql", "salt-master", "postfix"]
```

In this way you can have the pkg blacklisted and you control them.
No need to create a bot, the bot is good for coffee

**Comment by moio** [comment] 2018-05-23 10:40
@MalloZup are we sure dependencies are not automatically pulled in when using `additional_repos`? I am not sure about repo priorities.

If that is not the case then fantastic, we already have a workable tool!

**Comment by ktsamis** [comment] 2018-05-23 12:57
No, this means creating a separate job in jenkins for each and every SLES update that is in the queue of QAM that can be installed.  

All of those end up in SLES and if I want to test them separately I need to add each repo from each update (with the appropriate link that changes depending on products and IDs), detect the packages in the update and add those in the additional_packages. This means about 50 jobs in jenkins every day. Created new every day, run every day. We don't have the servers for this. 

This was solution 1 for which we don't have the servers and we still need a bot to create the right ```additional_repos``` and ```additional_packages```.

For example a single update job would be:
```
additional_repos {
    unreleased_update_7054= "http://download.suse.de/ibs/SUSE:/Maintenance:/7054/SUSE_Updates_SLE-SERVER_12-SP3_x86_64/"

additional_packages = ['libudev1', 'systemd-bash-completion', 'systemd-mini-devel', 'libudev-mini-devel', 'libudev-mini1', 'systemd-devel', 'systemd', 'libsystemd0-32bit', 'systemd-sysvinit', 'libsystemd0', 'systemd-32bit', 'udev', 'systemd-mini', 'libudev-devel', 'libudev1-32bit', 'udev-mini']
```

And this would need to run the testsuite, then another job with different repo and packages. If we run them serially the suite needs to run 24/7 and I am still not sure that it would manage all the updates that come in everyday. Maybe, maybe not. I don't have the number of updates that come in everyday. If they need to run (a few) in parallel we need resources. Maybe in the cloud?

**Comment by ktsamis** [comment] 2018-05-23 12:58
The dependencies are not really important. They should be satisfied by the normal updates repo or the Maint repo that is added.

**Comment by MalloZup** [comment] 2018-05-23 13:12
@ktsamis  i think you misunderstood, we are discussing unreleased updates, which means we are not adding MU or test this.

Here the workflow is folliwing, as i wrote before:

have only 1 jenkins job with Manager released and have the repo Unreleased_repo with Filtered pkgs which prevent random situations or much noise

**Comment by ktsamis** [comment] 2018-05-23 14:56
@MalloZup Ok let's say that we are not talking about SUMA Maintenance updates (I wasn't), we still need the repositories for each of the unreleased maintenance updates. The ```unreleased_updates = true```  means that about 50 updates will be installed. Let's say that with this option I see that bootstrapping is broken and I have about 150 failures in the testsuite. How do I know which of these 50 SLE updates is responsible to make sure that it is rejected? 

If we put separate repositories in ```additional_repos``` for each update and have a different run for each, we immediately know that the one that shows the failures is responsible and we reject. 

For review this would be easy. All other jobs have green tests or the same number of failures and the one job with:

```additional_repos = "http://download.suse.de/ibs/SUSE:/Maintenance:/7054/SUSE_Updates_SLE-SERVER_12-SP3_x86_64/" ``` has 150 failures more. 

Then we know that the job with this repo, and the update 7054 is the one with the problem and needs rejection.

The ```unreleased_updates``` does not only update major packages for SUMA from what I understand, it takes the repo where all updates in QAM are accumulated and installs all of them. Which of these would be responsible for any failure? Am I misunderstanding the option?

**Comment by moio** [comment] 2018-05-24 08:46
Trying to wrap up and clearing up points I see so far.

 * > One way would be to have a bot to pick up each update, install it and run the testsuite

That would be optimal, but let's move towards that one step at a time. To get any debugging started, we need a way to selectively enable individual updates - at the moment it's all-or-nothing. We can assume we always test with `unreleased_updates = true`, and when something breaks, we need to have a way to determine where the problem lies. Sometimes we can tell by just looking at the package list and some guesswork - try to avoid updating a package or two and see if that helps. Of course we can do a bit of manual testing, but at some point we want to re-run the testsuite, and we likely need some sumaform support to do that.

Just to make it clear: **this** is the matter under discussion here - a possible new feature in sumaform. All else (workflows, automated CI setups, etc.) does not belong to a sumaform issue, so let's try to keep focus.

Going forward, my assumption will be that we are looking at a user that manually wants to run the testsuite with a subset of the available unreleased upgrades.

 * using the following **will not work**:

```hcl
module "u" {
  source = "./modules/libvirt/suse_manager"
  base_configuration = "${module.base.configuration}"

  name = "u"
  version = "3.1-nightly"
  image = "sles12sp3"

  use_unreleased_updates = false
  additional_repos {
    unreleased_updates = "http://mirror.tf.local/ibs/SUSE:/Maintenance:/Test:/SLE-SERVER:/12-SP3:/x86_64/update/"
  }
  additional_packages = ["postfix"]
}
```

What `additional_repos` does is to add a repo early in the deployment process. When sumaform installs the SUSE Manager Server pattern, all available repos will be considered as sources of dependency packages - IOW this will happily pull in anything from `unreleased_updates` including the usual suspects: Apache, Tomcat, Postfix... Even if base SLES packages remain non-upgraded, SUSE Manager dependencies will be, and those are the most typical ones to break. We really need one or more different repos.

 * using the following **is expected to work**:

```hcl
module "u" {
  source = "./modules/libvirt/suse_manager"
  base_configuration = "${module.base.configuration}"

  name = "u"
  version = "3.1-nightly"
  image = "sles12sp3"

  use_unreleased_updates = false
  use_released_updates = true
  additional_repos {
    unreleased_update_7054= "http://download.suse.de/ibs/SUSE:/Maintenance:/7054/SUSE_Updates_SLE-SERVER_12-SP3_x86_64/"
    unreleased_update_ ....
  }
}
```

This will pull in only updates in the specified `additional_repos`. Which is already a step ahead: when we see the testsuite failing, we can check http://maintenance.suse.de/, take an educated guess and produce a shortlist of URLs to be shortened until we found the cause.

Please note the use of flags here: if either `use_released_updates` or `use_unreleased_updates` are true, a `zypper up` is run and all packages are updated. In case `use_unreleased_updates` is true, an extra `SUSE:/Maintenance:/Test:` repo is also added (before anything else). In any case, the pattern installation will pull in updated dependencies from whatever repos are defined, including those in `additional_repos`.


To wrap up, are we OK with the workaround described above, or do we need an extra sumaform functionality? In the latter case, how could that look like?

The only thing I can think about is a repo-filtering functionality - allow one to define a repo in terms of another repo plus a blacklist (or whitelist) of packages or patches.

**Comment by MalloZup** [comment] 2018-05-28 07:48
from my pov i am ok with 

```hcl
module "u" {
  source = "./modules/libvirt/suse_manager"
  base_configuration = "${module.base.configuration}"

  name = "u"
  version = "3.1-nightly"
  image = "sles12sp3"

  use_unreleased_updates = false
  use_released_updates = true
  additional_repos {
    unreleased_update_7054= "http://download.suse.de/ibs/SUSE:/Maintenance:/7054/SUSE_Updates_SLE-SERVER_12-SP3_x86_64/"
    unreleased_update_ ....
  }
}
```
this approach would work already, and we can even add selected pkg.

from my pov the problem is only to define a ci pipeline/mechanism which would need to read from a up2date list the repositories,  update them and implement the repo adding worfklow in terraform hcl.

Also filtering them, like add only 1 by one or 2 by 2 or all togheter.

**Comment by moio** [comment] 2018-05-28 07:49
@ktsamis if you are OK with the previous comment I am closing this issue as no changes in sumaform would be required.

**Closed** 2018-05-28 09:49 UTC
