### ISSUE TITLE
ensure that server ( and clients) run with latest pkgs from sles, for tests-machines

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#128] opened 2017-06-14 16:34 UTC
- [ ] update all pkgs on server with ```upgrade_all_packages = "true" ```

**Comment by moio** [comment] 2017-06-15 06:03
@MalloZup I think it is also a matter on how you want to conduct tests - use the latest packages and you will find some bugs, use outdated ones and you will find others (or at least, you will be able to predict when customers open service requests that can be closed by recommending upgrades).

At the moment, it is by design that sumaform machines start with old packages ("as old as possible"), to give the possibility to selectively upgrade whatever is needed for the use case via Salt configuration. Some time ago we changed that policy to upgrade Salt only, because otherwise other states would not run correctly, and only recently we extended that policy to Zypper on SUSE systems.

https://github.com/moio/sumaform/blob/master/salt/default/init.sls#L5

We need a new configuration flag (eg. `upgrade_all_packages`, that applies to most if not all modules) that runs [pkg.uptodate](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.uptodate) there.

**Comment by MalloZup** [comment] 2017-06-15 07:31
Thz moio, yes i know this up2date pb can be solved with the flag var.

**Comment by Bischoff** [comment] 2017-06-15 12:06
>  I think it is also a matter on how you want to conduct tests - use the latest packages and you will find some bugs, use outdated ones and you will find others (or at least, you will be able to predict when customers open service requests that can be closed by recommending upgrades).

Yes. That was how I designed SLEnkins quite long ago - provide the basic system and let the people update if they wish, like they wish. Reasoning behind is that it's always simpler to add than to remove.

**Comment by MalloZup** [comment] 2017-06-15 14:44
@moio, afaik  the update_all_pkgs at moment will update all pkg at the end of the install. To simulate more an iso scenario, we might install all the pkg before the install.

**Comment by moio** [comment] 2017-06-15 14:46
Inserting the call in the place outlined above will update all packages before any installation (`default` is called by sumaform on its own before anything else).

**Comment by MalloZup** [comment] 2017-06-15 14:49
ok thx! i have updated then the tasks

**Comment by moio** [comment] 2017-06-23 13:19
PR #114 does what you need and more: it also uses SLES packages currently in QA. The flag should definitely be turned on for automated testsuites:

https://github.com/moio/sumaform/blob/master/README_ADVANCED.md#use-suse-linux-enterprise-unreleased-test-packages

Closing this issue!

**Closed by moio** 2017-06-23 13:19 UTC

**Comment by Bischoff** [comment] 2017-06-24 09:55
"currently in qa": where does it take them from?

**Comment by MalloZup** [comment] 2017-06-24 10:32
@Bischoff  the update that @moio means, are packages "unreleased" from QA-Maintenance.

Basically, this pkg are UNRELEASED-UPDATES. Take like for SLES-12SP2, before the get out to customers.
So we can say in suse-mgr, that this UPDATE for SLES- is unstable and must not go out.

I think QA is more generic, and the description should be detailed better.

Basically we are doing the job of qa-maintanance, but it is kind interesting for us in suse-mgr, because we can prevent bug like we had with apache2

**Comment by Bischoff** [comment] 2017-06-24 11:33
aaah, QAM. Got it now.

Yes, please replace "QA" with "QAM" in documentation to avoid such confusions :-) .

**Comment by moio** [comment] 2017-06-27 06:42
1e15526
