### ISSUE TITLE
[testsuite]: git clone fail even with option.

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#24] opened 2016-11-23 14:59 UTC
Tested recently, with the new option from this PR

https://github.com/moio/sumaform/pull/22

After 20 min, we have the error described.

Here is some advice: 

https://confluence.atlassian.com/stashkb/git-clone-fails-error-rpc-failed-result-56-http-code-200-693897332.html

It seems that is a specif networking problem/issue. As workaround they say to switch to ssh, or disable firewall.

**Comment by MalloZup** [comment] 2016-11-23 15:13
ok, i'm testing with the archive option

**Comment by MalloZup** [comment] 2016-11-23 17:21
https://github.com/moio/sumaform/pull/25, maybe should fix

**Comment by moio** [comment] 2016-11-24 07:46
> It seems that is a specif networking problem/issue. As workaround they say to switch to ssh, or disable firewall.

Indeed I cannot reproduce such error in my setup. This does not seem to be a sumaform issue, but rather a networking one, so I am closing this.

Thanks for reporting and trying more robust workarounds anyway!

**Closed by moio** 2016-11-24 07:46 UTC
